import { X } from "lucide-react"
import "./TemplatesPanel.css"

export interface CircuitTemplate {
  id: string
  name: string
  hindiName: string
  description: string
  code: string
  level: string
}

export const CIRCUIT_TEMPLATES: CircuitTemplate[] = [
  { id: "led", name: "LED indicator", hindiName: "LED indicator", description: "A safe beginner-friendly LED circuit", level: "Starter", code: `circuit.add(\n  <board width="30mm" height="20mm">\n    <resistor name="R1" resistance="1k" footprint="0402" pcbX={-6} pcbY={0} />\n    <led name="LED1" color="red" footprint="0603" pcbX={6} pcbY={0} />\n    <trace name="T1" from="net.VCC" to=".R1 > .pin1" />\n    <trace name="T2" from=".R1 > .pin2" to=".LED1 > .anode" />\n    <trace name="T3" from=".LED1 > .cathode" to="net.GND" />\n  </board>\n)` },
  { id: "button", name: "Button + LED", hindiName: "Button se LED", description: "Learn input, output, and a current-limiting resistor", level: "Starter", code: `circuit.add(\n  <board width="35mm" height="22mm">\n    <pushbutton name="SW1" footprint="pushbutton" pcbX={-8} pcbY={0} />\n    <resistor name="R1" resistance="1k" footprint="0402" pcbX={0} pcbY={0} />\n    <led name="LED1" color="green" footprint="0603" pcbX={8} pcbY={0} />\n    <trace name="T1" from="net.VCC" to=".SW1 > .pin1" />\n    <trace name="T2" from=".SW1 > .pin2" to=".R1 > .pin1" />\n    <trace name="T3" from=".R1 > .pin2" to=".LED1 > .anode" />\n    <trace name="T4" from=".LED1 > .cathode" to="net.GND" />\n  </board>\n)` },
  { id: "rgb-style", name: "Dual LED indicators", hindiName: "Do LED indicator", description: "Compare two outputs with separate current-limiting resistors", level: "Starter", code: `circuit.add(\n  <board width="40mm" height="22mm">\n    <resistor name="R1" resistance="1k" footprint="0402" pcbX={-10} pcbY={0} />\n    <led name="LED1" color="red" footprint="0603" pcbX={-3} pcbY={0} />\n    <resistor name="R2" resistance="2.2k" footprint="0402" pcbX={5} pcbY={0} />\n    <led name="LED2" color="blue" footprint="0603" pcbX={12} pcbY={0} />\n    <trace name="T1" from="net.VCC" to=".R1 > .pin1" />\n    <trace name="T2" from=".R1 > .pin2" to=".LED1 > .anode" />\n    <trace name="T3" from=".LED1 > .cathode" to="net.GND" />\n    <trace name="T4" from="net.VCC" to=".R2 > .pin1" />\n    <trace name="T5" from=".R2 > .pin2" to=".LED2 > .anode" />\n    <trace name="T6" from=".LED2 > .cathode" to="net.GND" />\n  </board>\n)` },
  { id: "filter", name: "RC low-pass filter", hindiName: "RC signal filter", description: "See how resistor and capacitor shape a signal", level: "Intermediate", code: `circuit.add(\n  <board width="35mm" height="22mm">\n    <resistor name="R1" resistance="10k" footprint="0402" pcbX={-6} pcbY={0} />\n    <capacitor name="C1" capacitance="100nF" footprint="0402" pcbX={6} pcbY={0} />\n    <trace name="T1" from="net.SIGNAL_IN" to=".R1 > .pin1" />\n    <trace name="T2" from=".R1 > .pin2" to="net.SIGNAL_OUT" />\n    <trace name="T3" from="net.SIGNAL_OUT" to=".C1 > .pin1" />\n    <trace name="T4" from=".C1 > .pin2" to="net.GND" />\n  </board>\n)` },
  { id: "divider", name: "Voltage divider", hindiName: "Voltage divider", description: "Make a smaller reference voltage with two resistors", level: "Intermediate", code: `circuit.add(\n  <board width="30mm" height="25mm">\n    <resistor name="R1" resistance="10k" footprint="0402" pcbX={0} pcbY={-7} />\n    <resistor name="R2" resistance="10k" footprint="0402" pcbX={0} pcbY={7} />\n    <testpoint name="TP1" footprintVariant="pad" padShape="circle" pcbX={9} pcbY={0} />\n    <trace name="T1" from="net.VCC" to=".R1 > .pin1" />\n    <trace name="T2" from=".R1 > .pin2" to="net.VMID" />\n    <trace name="T3" from="net.VMID" to=".R2 > .pin1" />\n    <trace name="T4" from=".R2 > .pin2" to="net.GND" />\n    <trace name="T5" from=".TP1 > .pin1" to="net.VMID" />\n  </board>\n)` },
  { id: "transistor-switch", name: "Transistor switch", hindiName: "Transistor se LED", description: "Use a transistor as an electronic switch", level: "Intermediate", code: `circuit.add(\n  <board width="40mm" height="25mm">\n    <transistor name="Q1" type="npn" footprint="sot23" pcbX={0} pcbY={0} />\n    <resistor name="R1" resistance="1k" footprint="0402" pcbX={-9} pcbY={-6} />\n    <resistor name="R2" resistance="1k" footprint="0402" pcbX={8} pcbY={-6} />\n    <led name="LED1" color="yellow" footprint="0603" pcbX={8} pcbY={7} />\n    <trace name="T1" from="net.VCC" to=".R2 > .pin1" />\n    <trace name="T2" from=".R2 > .pin2" to=".LED1 > .anode" />\n    <trace name="T3" from=".LED1 > .cathode" to=".Q1 > .collector" />\n    <trace name="T4" from=".Q1 > .emitter" to="net.GND" />\n    <trace name="T5" from="net.INPUT" to=".R1 > .pin1" />\n    <trace name="T6" from=".R1 > .pin2" to=".Q1 > .base" />\n  </board>\n)` },
  { id: "diode-protection", name: "Diode protection", hindiName: "Reverse polarity protection", description: "Learn how a diode protects a power input", level: "Intermediate", code: `circuit.add(\n  <board width="38mm" height="22mm">\n    <diode name="D1" variant="schottky" footprint="sod123" pcbX={-7} pcbY={0} />\n    <fuse name="F1" currentRating="500mA" footprint="0603" pcbX={4} pcbY={0} />\n    <capacitor name="C1" capacitance="10uF" footprint="0805" pcbX={13} pcbY={0} />\n    <trace name="T1" from="net.VIN" to=".D1 > .anode" />\n    <trace name="T2" from=".D1 > .cathode" to="net.PROTECTED" />\n    <trace name="T3" from="net.PROTECTED" to=".F1 > .pin1" />\n    <trace name="T4" from=".F1 > .pin2" to=".C1 > .pin1" />\n    <trace name="T5" from=".C1 > .pin2" to="net.GND" />\n  </board>\n)` },
  { id: "battery-led", name: "Battery power board", hindiName: "Battery se LED", description: "A portable power source with an LED indicator", level: "Starter", code: `circuit.add(\n  <board width="40mm" height="22mm">\n    <battery name="BAT1" voltage="3.7" standard="18650" footprint="0805" pcbX={-10} pcbY={0} connections={{ pos: "net.VBAT", neg: "net.GND" }} />\n    <resistor name="R1" resistance="1k" footprint="0402" pcbX={0} pcbY={0} />\n    <led name="LED1" color="blue" footprint="0603" pcbX={10} pcbY={0} />\n    <trace name="T1" from="net.VBAT" to=".R1 > .pin1" />\n    <trace name="T2" from=".R1 > .pin2" to=".LED1 > .anode" />\n    <trace name="T3" from=".LED1 > .cathode" to="net.GND" />\n  </board>\n)` },
  { id: "pot-control", name: "Potentiometer control", hindiName: "Knob se control", description: "Explore variable resistance and an LED output", level: "Intermediate", code: `circuit.add(\n  <board width="42mm" height="24mm">\n    <potentiometer name="POT1" maxResistance="10k" footprint="0805" pcbX={-8} pcbY={0} />\n    <resistor name="R1" resistance="1k" footprint="0402" pcbX={5} pcbY={0} />\n    <led name="LED1" color="green" footprint="0603" pcbX={14} pcbY={0} />\n    <trace name="T1" from="net.VCC" to=".POT1 > .pin1" />\n    <trace name="T2" from=".POT1 > .pin2" to="net.DIAL" />\n    <trace name="T3" from="net.DIAL" to=".R1 > .pin1" />\n    <trace name="T4" from=".R1 > .pin2" to=".LED1 > .anode" />\n    <trace name="T5" from=".LED1 > .cathode" to="net.GND" />\n    <trace name="T6" from=".POT1 > .pin3" to="net.GND" />\n  </board>\n)` },
  { id: "rc-simulation", name: "RC transient simulation", hindiName: "Signal simulation", description: "Run a time-based charge and discharge experiment", level: "Advanced", code: `circuit.add(\n  <board width="38mm" height="24mm">\n    <voltagesource name="V1" voltage="5" footprint="0402" connections={{ pin1: "net.VBAT", pin2: "net.GND" }} />\n    <resistor name="R1" resistance="1k" footprint="0402" pcbX={-6} pcbY={0} />\n    <capacitor name="C1" capacitance="47uF" footprint="0805" pcbX={7} pcbY={0} />\n    <voltageprobe name="Vout" connectsTo=".C1 > .pin1" />\n    <trace name="T1" from="net.VBAT" to=".R1 > .pin1" />\n    <trace name="T2" from=".R1 > .pin2" to="net.VOUT" />\n    <trace name="T3" from="net.VOUT" to=".C1 > .pin1" />\n    <trace name="T4" from=".C1 > .pin2" to="net.GND" />\n    <analogtransientsimulation duration="20ms" />\n  </board>\n)` },
  { id: "buck-boost", name: "Inverting buck-boost", hindiName: "Power converter", description: "An advanced power topology with MOSFET, inductor, and diode", level: "Advanced", code: `circuit.add(\n  <board width="55mm" height="35mm">\n    <mosfet name="Q1" channelType="p" mosfetMode="enhancement" footprint="sot23" pcbX={0} pcbY={4} />\n    <inductor name="L1" inductance="47uH" footprint="0805" pcbX={12} pcbY={0} />\n    <diode name="D1" variant="schottky" footprint="sod123" pcbX={12} pcbY={9} connections={{ anode: "net.GND", cathode: "net.SW" }} />\n    <capacitor name="C1" capacitance="100uF" footprint="0805" pcbX={23} pcbY={0} />\n    <resistor name="R1" resistance="10k" footprint="0402" pcbX={-8} pcbY={10} />\n    <trace name="T1" from="net.VIN" to=".Q1 > .source" />\n    <trace name="T2" from=".Q1 > .drain" to="net.SW" />\n    <trace name="T3" from="net.SW" to=".L1 > .pin1" />\n    <trace name="T4" from=".L1 > .pin2" to="net.VOUT_NEG" />\n    <trace name="T5" from="net.GND" to=".C1 > .pin1" />\n    <trace name="T6" from=".C1 > .pin2" to="net.VOUT_NEG" />\n    <trace name="T7" from="net.VIN" to=".R1 > .pin1" />\n    <trace name="T8" from=".R1 > .pin2" to=".Q1 > .gate" />\n  </board>\n)` },
]

interface TemplatesPanelProps { onClose: () => void; onSelect: (template: CircuitTemplate) => void }

export function TemplatesPanel({ onClose, onSelect }: TemplatesPanelProps) {
  return <div className="templates-overlay" onClick={onClose}>
    <aside className="templates-panel" onClick={(event) => event.stopPropagation()} role="dialog" aria-label="Circuit templates">
      <div className="templates-header"><div><div className="templates-eyebrow">Start learning</div><h2>Template gallery</h2></div><button className="templates-close" onClick={onClose} aria-label="Close templates"><X size={18} /></button></div>
      <p className="templates-note">Pick a working circuit, then change one thing and run it. Hindi names make discovery easier in classrooms.</p>
      <div className="template-list">{CIRCUIT_TEMPLATES.map((template) => <button className="template-card" key={template.id} onClick={() => onSelect(template)}><span className="template-card-top"><strong>{template.name}</strong><span>{template.level}</span></span><span className="template-hindi">{template.hindiName}</span><span className="template-description">{template.description}</span><span className="template-action">Load circuit</span></button>)}</div>
    </aside>
  </div>
}